import "dotenv/config";
import { randomUUID } from "node:crypto";
import { expect, test } from "./fixtures";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("可选作品信息框、诠释者编辑、讨论失效锚点与搜索回复定位", async ({ page }) => {
  test.setTimeout(120_000);
  const signed = await page.request.post("/api/auth/sign-in/email", { data: { email: process.env.SEED_ADMIN_EMAIL, password: process.env.SEED_ADMIN_PASSWORD } });
  expect(signed.ok()).toBe(true);
  const title = `MVP ${randomUUID()}`;
  const create = async (data: object) => {
    const response = await page.request.post("/api/submissions", { data });
    expect(response.status()).toBe(201); return response.json();
  };
  const term = await create({ kind: "new_term", title });
  await page.goto(term.href);
  await expect(page.getByText("关键文本", { exact: true })).toHaveCount(0);
  await page.getByRole("link", { name: "编辑词条信息", exact: true }).click();
  await page.getByRole("button", { name: "添加作品" }).click();
  await page.getByLabel("作品名 1", { exact: true }).fill("第一部作品");
  await page.getByRole("button", { name: "添加作品" }).click();
  await page.getByLabel("作品名 2", { exact: true }).fill("第二部作品");
  await page.getByRole("button", { name: "上移", exact: true }).nth(1).click();
  await expect(page.getByText(/草稿已自动保存/)).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("作品名 1", { exact: true })).toHaveValue("第二部作品");
  await page.getByRole("button", { name: "提交（直接生效）", exact: true }).click();
  await page.getByRole("link", { name: "查看页面 →" }).click();
  await expect(page.locator("aside").filter({ hasText: "关键文本" })).toContainText("第二部作品第一部作品");
  const interpreter = await create({ kind: "new_interpreter", title: `Reader ${title}` });
  await page.goto(interpreter.href);
  await page.getByRole("link", { name: "编辑诠释者信息" }).click();
  await page.getByRole("button", { name: "添加作品" }).click();
  await page.getByLabel("作品名 1", { exact: true }).fill("诠释者代表作品");
  await page.getByRole("button", { name: "提交（直接生效）", exact: true }).click();
  await page.getByRole("link", { name: "查看页面 →" }).click();
  await expect(page.locator("aside")).toContainText("诠释者代表作品");
  const perspective = await create({ kind: "new_perspective", termId: term.pageId, interpreterId: interpreter.pageId, content: "讨论的公开视角" });
  const floorResponse = await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, perspectiveId: perspective.pageId, content: "已有讨论" } });
  expect(floorResponse.status()).toBe(201);
  const floor = await floorResponse.json();
  for (let i = 0; i < 12; i++) await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, content: `填充楼层 ${i} ` + "讨论文字。".repeat(40) } });
  const needle = `uniquereply${Date.now()}`;
  const replyResponse = await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, parentId: floor.id, content: needle } });
  expect(replyResponse.status()).toBe(201);
  const reply = await replyResponse.json();
  await page.goto(`/search?q=${needle}`);
  const hit = page.locator(`a[href$="#floor-${reply.id}"]`);
  await expect(hit).toBeVisible();
  await hit.click();
  await expect(page.locator(`#floor-${reply.id}`)).toContainText(needle);
  await expect(page.locator(`#floor-${reply.id}`)).toBeInViewport();
  expect((await page.request.post(`/api/admin/pages/${interpreter.pageId}`, { data: { action: "delete" } })).ok()).toBe(true);
  await page.reload();
  await expect(page.locator(`#floor-${floor.id}`).locator(`a[href="${perspective.href}"]`)).toHaveCount(0);
  expect((await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, perspectiveId: perspective.pageId, content: "失效锚点" } })).status()).toBe(400);
  await page.request.post(`/api/admin/pages/${interpreter.pageId}`, { data: { action: "restore" } });
  await page.reload();
  await expect(page.locator(`#floor-${floor.id}`).locator(`a[href="${perspective.href}"]`)).toBeVisible();
});

test("归并后公开正文、讨论回复、分类和双链仍可阅读", async ({ page }) => {
  test.skip(process.env.MVP_MIGRATION_E2E !== "1" || !new URL(process.env.DATABASE_URL!).pathname.startsWith("/phoskywiki_review_"), "归并验收仅允许显式选择的隔离数据库");
  test.setTimeout(90_000);
  await page.request.post("/api/auth/sign-in/email", { data: { email: process.env.SEED_ADMIN_EMAIL, password: process.env.SEED_ADMIN_PASSWORD } });
  const title = `Merged ${randomUUID()}`;
  const create = async (data: object) => { const response = await page.request.post("/api/submissions", { data }); expect(response.status()).toBe(201); return response.json(); };
  const a = await create({ kind: "new_term", title: `${title}（哲学）` });
  const shared = await create({ kind: "new_interpreter", title: `合并诠释者 ${title}` });
  const sharedName = `合并诠释者 ${title}`;
  const first = await create({ kind: "new_perspective", termId: a.pageId, interpreterId: shared.pageId, content: "哲学公开解释\n\n[哲学出处][ref]\n\n[ref]: https://example.org/philosophy" });
  const b = await create({ kind: "new_term", title: `${title}（经济学）` });
  const second = await create({ kind: "new_perspective", termId: b.pageId, interpreterId: shared.pageId, content: `经济学公开解释\n\n[经济出处][ref]\n\n[ref]: ${a.href}` });
  const thinker = await create({ kind: "new_interpreter", title: `独立诠释者 ${title}` });
  const unique = await create({ kind: "new_perspective", termId: b.pageId, interpreterId: thinker.pageId, content: "独立视角正文保留" });
  const sourceTerm = await create({ kind: "new_term", title: `Source ${title}` });
  const source = await create({ kind: "new_perspective", termId: sourceTerm.pageId, interpreterId: shared.pageId, content: `普通 [[${title}（经济学）]]，精确 [[${title}（经济学）|合并视角@${sharedName}]]` });
  const sharedPerspectiveId = second.pageId;
  const floor = await (await page.request.post("/api/discussion/posts", { data: { termId: b.pageId, perspectiveId: sharedPerspectiveId, content: "迁移公开楼层" } })).json();
  const reply = await (await page.request.post("/api/discussion/posts", { data: { termId: b.pageId, parentId: floor.id, content: "迁移公开回复" } })).json();
  const folder = await mkdtemp(join(tmpdir(), "phosky-browser-merge-"));
  await writeFile(join(folder, "groups.json"), JSON.stringify([{ title, sourceTitles: [`${title}（哲学）`, `${title}（经济学）`] }]));
  await writeFile(join(folder, "fixture.txt"), "disposable HTTP-created fixture");
  // 子进程会重载 .env；置空 MEILI_HOST 防止 apply 末尾的 reindexAll 把隔离库内容写进开发索引（与集成测试的 run() 同法）
  await promisify(execFile)(process.execPath, ["--conditions", "react-server", "--import", "tsx", "scripts/consolidate-mvp.ts", "--database", new URL(process.env.DATABASE_URL!).pathname.slice(1), "--groups", join(folder, "groups.json"), "--apply", "--backup", join(folder, "fixture.txt")], { env: { ...process.env, MEILI_HOST: "" } });
  await page.goto(`/term/${a.pageId}`);
  await expect(page.getByRole("heading", { level: 1, name: title })).toBeVisible();
  await page.goto(first.href);
  await expect(page.locator(".wiki-content")).toContainText("哲学公开解释");
  await expect(page.locator(".wiki-content")).toContainText("经济学公开解释");
  await expect(page.locator(".wiki-content").getByRole("link", { name: "哲学出处", exact: true })).toHaveAttribute("href", "https://example.org/philosophy");
  await page.locator(".wiki-content").getByRole("link", { name: "经济出处", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1, name: title })).toBeVisible();
  await page.getByRole("link", { name: /讨论区（/ }).click();
  await expect(page.locator(`#floor-${floor.id}`)).toContainText("迁移公开楼层");
  await expect(page.locator(`#floor-${reply.id}`)).toContainText("迁移公开回复");
  await page.locator(`#floor-${floor.id}`).getByRole("link", { name: `${sharedName}论${title}` }).click();
  await expect(page.locator(".wiki-content")).toContainText("经济学公开解释");
  await page.goto(unique.href);
  await expect(page.locator(".wiki-content")).toContainText("独立视角正文保留");
  await page.goto(source.href);
  await page.locator(".wiki-content").getByRole("link", { name: `${title}（经济学）`, exact: true }).click();
  await expect(page.getByRole("heading", { level: 1, name: title })).toBeVisible();
  await page.goto(source.href);
  await page.getByRole("link", { name: "合并视角", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1, name: `${sharedName}论${title}` })).toBeVisible();
  expect((await page.request.get(b.href)).status()).toBe(404);
  const hits = await (await page.request.get(`/api/search?q=${encodeURIComponent(title)}&type=term`)).json();
  expect(hits.hits.some((h: { pageId: number }) => h.pageId === b.pageId)).toBe(false);
  expect(hits.hits.some((h: { pageId: number }) => h.pageId === a.pageId)).toBe(true);
});

test("并发发布期间编辑 SSR 的正文与提交基准始终属于同一修订", async ({ page }) => {
  test.setTimeout(90_000);
  await page.request.post("/api/auth/sign-in/email", { data: { email: process.env.SEED_ADMIN_EMAIL, password: process.env.SEED_ADMIN_PASSWORD } });
  const title = `Snapshot ${randomUUID()}`;
  const create = async (data: object) => { const response = await page.request.post("/api/submissions", { data }); expect(response.status()).toBe(201); return response.json(); };
  const term = await create({ kind: "new_term", title });
  const thinker = await create({ kind: "new_interpreter", title: `Snapshot reader ${title}` });
  const perspective = await create({ kind: "new_perspective", termId: term.pageId, interpreterId: thinker.pageId, content: "Snapshot 0" });
  const id = perspective.pageId;
  await page.goto(`/edit/${id}`);
  await page.route("**/api/submissions", route => route.fulfill({ status: 409, json: { error: "观察提交载荷，保留草稿" } }));
  for (let round = 0; round < 5; round++) {
    await page.evaluate(() => localStorage.clear());
    const write = (async () => {
      for (let i = 0; i < 4; i++) {
        const state = await (await page.request.get(`/api/pages/${id}/history`)).json();
        const result = await page.request.post("/api/submissions", { data: { kind: "edit", pageId: id, baseRevisionId: state.revisions[0].id, content: `Snapshot ${round}-${i}` } });
        expect(result.status()).toBe(201);
      }
    })();
    await page.goto(`/edit/${id}`);
    await expect(page.getByRole("textbox", { name: "正文（Markdown）" })).toBeVisible();
    const submitted = page.waitForRequest(r => r.url().endsWith("/api/submissions") && r.method() === "POST");
    await page.getByRole("button", { name: "提交（直接生效）", exact: true }).click();
    const payload = (await submitted).postDataJSON();
    await write;
    const state = await (await page.request.get(`/api/pages/${id}/history`)).json();
    expect(state.revisions.find((r: { id: number }) => r.id === payload.baseRevisionId).content).toBe(payload.content);
  }
});
